### PR TITLE
Support dropping foreign key

### PR DESCRIPTION
**Pull request by youpy**
- Add `DropKeyMapper` that returns keywords in foreign key deletion based on key type

### CODE REVIEW

**Comment by Fs02** [comment]
Hi, thanks for the PR

can you give example what's the use case for mapper? thanks

**Comment by youpy** [comment]
Thanks for the review.

> can you give example what's the use case for mapper?

For the MySQL adapter, `DropKeyMapper` would look like this:

```go
func DropKeyMapper(keyType rel.KeyType) string {
  if keyType == rel.ForeignKey {
    // see https://dev.mysql.com/doc/refman/8.0/ja/alter-table.html
    return "FOREIGN KEY"
  }

  // unsupported key type
  // (maybe we should return an error here)
  return ""
}
```

**Review by Fs02 — APPROVED** [review]
LGTM, Thanks

**Comment by Fs02** [comment]
will you update the other adapters too?

**Comment by youpy** [comment]
> will you update the other adapters too?

yes I will.

**Pull request merged**
