### PR TITLE
Add query args to instrumentation

### PR DESCRIPTION
**Pull request by wakamenod**
I think it would be useful to have query parameters in the log output as well.
What do you think?

### CODE REVIEW

**Comment by Fs02** [comment]
can you update this to use latest master?

**Comment by wakamenod** [comment]
@Fs02

 Hi, thanks very much for your support.

I merged latest master into the branch. Does it suffice?

**Comment by Fs02** [comment]
I mean, update with latest rel@master (and fix the build error)

**Comment by wakamenod** [comment]
sorry that I misunderstood what you mean. 
the build error has been fixed.

**Review by Fs02 — APPROVED** [review]
LGTM, Thank you

**Pull request merged**
